-- Supabase SQL Editor에서 전체 실행하세요.

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  role text not null default 'user' check (role in ('user','admin')),
  created_at timestamptz not null default now()
);

create table if not exists public.restaurants (
  id bigint generated by default as identity primary key,
  name text not null,
  address text not null,
  lat double precision,
  lng double precision,
  walk_min integer check (walk_min is null or walk_min >= 0),
  menu text,
  phone text,
  naver_url text,
  kakao_url text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.reviews (
  id bigint generated by default as identity primary key,
  restaurant_id bigint not null references public.restaurants(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  rating integer not null check (rating between 1 and 5),
  content text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.menus (
  id bigint generated by default as identity primary key,
  restaurant_id bigint not null references public.restaurants(id) on delete cascade,
  name text not null,
  price integer,
  created_at timestamptz not null default now()
);

-- 신규 가입자 profile 자동 생성
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer set search_path = public
as $$
begin
  insert into public.profiles (id, role) values (new.id, 'user');
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row execute procedure public.handle_new_user();

-- updated_at 자동 갱신
create or replace function public.set_updated_at()
returns trigger language plpgsql as $$
begin new.updated_at = now(); return new; end; $$;
drop trigger if exists restaurants_set_updated_at on public.restaurants;
create trigger restaurants_set_updated_at before update on public.restaurants
for each row execute procedure public.set_updated_at();

alter table public.profiles enable row level security;
alter table public.restaurants enable row level security;
alter table public.reviews enable row level security;
alter table public.menus enable row level security;

-- profiles: 본인 profile만 읽기. role 변경은 SQL Editor에서만 하는 것을 권장.
drop policy if exists "profiles_select_own" on public.profiles;
create policy "profiles_select_own" on public.profiles
for select to authenticated using (id = auth.uid());

-- restaurants: 누구나 읽기 / 관리자만 쓰기
 drop policy if exists "restaurants_select_public" on public.restaurants;
create policy "restaurants_select_public" on public.restaurants
for select to anon, authenticated using (true);

drop policy if exists "restaurants_insert_admin" on public.restaurants;
create policy "restaurants_insert_admin" on public.restaurants
for insert to authenticated with check ((select role from public.profiles where id = auth.uid()) = 'admin');

drop policy if exists "restaurants_update_admin" on public.restaurants;
create policy "restaurants_update_admin" on public.restaurants
for update to authenticated using ((select role from public.profiles where id = auth.uid()) = 'admin') with check ((select role from public.profiles where id = auth.uid()) = 'admin');

drop policy if exists "restaurants_delete_admin" on public.restaurants;
create policy "restaurants_delete_admin" on public.restaurants
for delete to authenticated using ((select role from public.profiles where id = auth.uid()) = 'admin');

-- reviews: 누구나 읽기 / 로그인 사용자는 본인 이름으로 작성 / 본인 수정·삭제 / 관리자 전체 관리
 drop policy if exists "reviews_select_public" on public.reviews;
create policy "reviews_select_public" on public.reviews
for select to anon, authenticated using (true);

drop policy if exists "reviews_insert_own" on public.reviews;
create policy "reviews_insert_own" on public.reviews
for insert to authenticated with check (user_id = auth.uid());

drop policy if exists "reviews_update_own_or_admin" on public.reviews;
create policy "reviews_update_own_or_admin" on public.reviews
for update to authenticated using (user_id = auth.uid() or (select role from public.profiles where id = auth.uid()) = 'admin') with check (user_id = auth.uid() or (select role from public.profiles where id = auth.uid()) = 'admin');

drop policy if exists "reviews_delete_own_or_admin" on public.reviews;
create policy "reviews_delete_own_or_admin" on public.reviews
for delete to authenticated using (user_id = auth.uid() or (select role from public.profiles where id = auth.uid()) = 'admin');

-- menus: 누구나 읽기 / 관리자만 쓰기
 drop policy if exists "menus_select_public" on public.menus;
create policy "menus_select_public" on public.menus
for select to anon, authenticated using (true);

drop policy if exists "menus_insert_admin" on public.menus;
create policy "menus_insert_admin" on public.menus
for insert to authenticated with check ((select role from public.profiles where id = auth.uid()) = 'admin');

drop policy if exists "menus_update_admin" on public.menus;
create policy "menus_update_admin" on public.menus
for update to authenticated using ((select role from public.profiles where id = auth.uid()) = 'admin') with check ((select role from public.profiles where id = auth.uid()) = 'admin');

drop policy if exists "menus_delete_admin" on public.menus;
create policy "menus_delete_admin" on public.menus
for delete to authenticated using ((select role from public.profiles where id = auth.uid()) = 'admin');

-- 첫 관리자 지정 방법
-- 1) 웹에서 관리자 계정으로 회원가입
-- 2) 아래 SQL에서 이메일을 본인 관리자 이메일로 바꿔 실행
--
-- update public.profiles p
-- set role = 'admin'
-- from auth.users u
-- where p.id = u.id and u.email = '관리자이메일@example.com';
